name: shopping_list
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^3.0.0+1
  quiver: ^2.0.3
  sqflite:
  path:
  uuid: ^2.0.2
  injector: ^1.0.8
  cupertino_icons: ^0.1.2
  flutter_staggered_grid_view: "^0.3.0"

dev_dependencies:
  mockito: ^4.1.1
  test:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
